# Where the files will be downloaded
download_workdir: "/data/kraken-download/datasets"

# Credentials
drugbank_login: "my_email"
drugbank_password: "my_password"

affymetrix_login: "my_email"
affymetrix_password: "my_password"

biomodels_login: "my_email"
biomodels_password: "my_password"

bioportal_apikey: "my_apikey"
# From account...

datasets:
  - miriam

  #- clinicaltrials
  #- pharmgkb
  #- drugbank
  #- affymetrix
  #- biomodels
  #- bioportal
  #- chembl
  #- ctd
  #- dbpedia
  #- drugbank
  #- drugcentral
  #- genage
  #- gendr 
  #- genbank 
  #- goa 
  #- pdb
  #- hgnc
  #- interpro 
  #- homologene
  #- ipi 
  #- irefindex 
  #- kegg 
  #- lsr 
  #- mgi 
  #- miriam
  #- ncbigene 
  #- pharmgkb 
  #- pubchem 
  #- refseq 
  #- sider 
  #- taxonomy 
  #- uniprot 
  #- wikipathways
  #- wormbase
