drugbank_login: "my_email"
drugbank_password: "my_password"

affymetrix_login: "my_email"
affymetrix_password: "my_password"

biomodels_login: "my_email"
biomodels_password: "my_password"

datasets:
  - clinicaltrials
  #- pharmgkb
  #- drugbank
  #- affymetrix
  #- ctd
  #- dbpedia
  #- drugbank
  #- genage
  #- gendr 
  #- genbank 
  #- goa 
  #- hgnc
  #- interpro 
  #- homologene
  #- ipi 
  #- irefindex 
  #- kegg 
  #- lsr 
  #- mgi 
  #- ncbigene 
  #- pharmgkb 
  #- pubchem 
  #- refseq 
  #- sider 
  #- taxonomy 
  #- uniprot 
  #- wormbase
