# Where the files will be downloaded
download_workdir: "/data/kraken-download/datasets"

# Credentials
drugbank_login: "my_email"
drugbank_password: "my_password"

affymetrix_login: "my_email"
affymetrix_password: "my_password"

biomodels_login: "my_email"
biomodels_password: "my_password"

bioportal_apikey: "my_apikey"
# From account...

datasets:
  # XML
  - clinicaltrials
  - pubmed
  - interpro
  - bioproject
  - clinvar
  - dailymed
  - dbsnp
  - flybase
  - orphanet
  - pdb
  # TSV
  - stitch
  - pharmgkb
  - drugcentral
  - bindingdb
  - ncbigene
  - ndc
  - stitch
  - genage
  - string